#!/bin/bash
#
# Script to setup dot files in $HOME from .* files/dirs in dot_files repo.
#

unalias ls

BASE="${PWD#${HOME}/}"

cd $HOME

for i in $(ls -A1 -I '[a-zA-Z]*' -I '.git*' -I '.#*' ${BASE})
do
    tgt="./${BASE}/$i"
    lnk="$i"

    if [ -e ${lnk} ]
    then
	if [ -L ${lnk} ]
	then
	    echo "skip: symlink exists:              ${lnk} "
	else
	    echo "skip: file exists (not a symlink): ${lnk}"
	fi
	continue
    fi

    echo ln -s ${tgt} ${lnk}
    ln -s ${tgt} ${lnk}
done
