# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family                family="RobotoMono Nerd Font"
bold_font                  auto
italic_font                auto
bold_italic_font           auto

font_size                  12.0

#: }}}

#: Text cursor customization {{{

cursor_stop_blinking_after 15.0

#: }}}

#: Scrollback {{{

scrollback_lines           20000

#: }}}

#: Mouse {{{

copy_on_select             no
clear_selection_on_clipboard_loss yes

#: }}}

#: Terminal bell {{{

enable_audio_bell          no

#: }}}

#: Window layout {{{

remember_window_size       no
initial_window_width       1800
initial_window_height      1000

enabled_layouts            splits

window_border_width        3pt
window_margin_width        0
window_padding_width       2

#: }}}

#: Tab bar {{{

tab_bar_edge               top
tab_bar_style              slant
tab_title_template         "{index}: {title}"

#active_tab_foreground      #000
#active_tab_background      #eee
active_tab_font_style      bold
#inactive_tab_foreground    #444
#inactive_tab_background    #999
inactive_tab_font_style    normal

#: }}}

#: Color scheme {{{

dim_opacity                1.0

#include                    themes/modus-operandi-troth.conf
include                    themes/cupertino-base16-256.conf

#: }}}

#: Advanced {{{

shell                      /bin/bash -l
update_check_interval      0
allow_hyperlinks           no
shell_integration          disabled

#: }}}

#: Keyboard shortcuts {{{
#
#
# Keyboard Mappings
#

kitty_mod                  super+alt

# Split the current Window
map super+alt+5            launch --location=vsplit --cwd=current
map super+alt+'            launch --location=hsplit --cwd=current

# Move the active window in the indicated direction
map kitty_mod+shift+up     move_window up
map kitty_mod+shift+left   move_window left
map kitty_mod+shift+right  move_window right
map kitty_mod+shift+down   move_window down

# Switch focus to the neighboring window in the indicated direction
map kitty_mod+left         neighboring_window left
map kitty_mod+right        neighboring_window right
map kitty_mod+up           neighboring_window up
map kitty_mod+down         neighboring_window down

map kitty_mod+t            new_tab_with_cwd
map kitty_mod+shift+t      new_tab
map kitty_mod+ctrl+t       set_tab_title
map kitty_mod+ctrl+right   next_tab
map kitty_mod+ctrl+left    previous_tab
map kitty_mod+ctrl+up      select_tab

map kitty_mod+ctrl+c       copy_to_buffer a1
map kitty_mod+ctrl+v       paste_from_buffer a1

#: }}}
